### ISSUE TITLE
Secrets are enclosed by quotes

### ISSUE THREAD

**Issue by jansgescheit** [maxkpower/insomnia-bitwarden-secrets#2]
When I query a secret, the returned secret is enclosed in quotes.

This prevents you from using the secret e.g. in a request header or in a signature calculation.

### Bug

This example configuration for a authorization:

```json 
{
  [...]
  "signature": "{% bws 'getSecret' 'your-secret-uuid' %}"
}
```

```txt
x-signature:  {{ _.signature }}
```

Will endup in:

#### Config
```json 
{
  [...]
  "signature": ""my-secret-signature""
}
```

#### Header
```txt
x-signature: "my-secret-signature"
```

### Expectation

Expected is something like this
#### Config
```json 
{
  [...]
  "signature": "my-secret-signature"
}
```
#### Header
```txt
x-signature: my-secret-signature
```

**Comment by jansgescheit** [comment]
https://github.com/maxkpower/insomnia-bitwarden-secrets/blob/93fd5e2d82cb3c6391b04095fe2dfb38f6fc8dc5/app.js#L77

Quotes the result again

**Comment by maxkpower** [comment]
Thanks a lot for finding this! I think it should be fixed now when filtering for the value?

Im also thinking about just filtering by default, I can't really think of any use cases where users would need the full CLI output in Insomnia.

**Comment by jansgescheit** [comment]
I also think that you only need the value

**Comment by maxkpower** [comment]
Cool, I adjusted it accordingly.
